from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('icono', models.CharField(default='bi-box', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías', 'ordering': ['orden', 'nombre']},
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField(help_text='Precio público en CLP')),
                ('costo', models.PositiveIntegerField(default=0)),
                ('precio_b2d', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_pack', models.PositiveIntegerField(blank=True, null=True)),
                ('unidades_pack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, default='sin_lote', max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('lugar_stock', models.CharField(blank=True, max_length=80)),
                ('precio_volumen', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_minima_volumen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pronto_a_vencer', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('edad_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='productos', to='miprimerapp.categoria')),
            ],
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos', 'ordering': ['categoria', 'nombre']},
        ),
        migrations.CreateModel(
            name='ConsultaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre_clinica', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=5)),
                ('tipo_consulta', models.CharField(default='info', max_length=15)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto', 'ordering': ['-fecha']},
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField()),
                ('sitio_web', models.URLField(blank=True)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('cargo_contacto', models.CharField(blank=True, max_length=80)),
                ('medio_contacto', models.CharField(choices=[('whatsapp','WhatsApp'),('llamada','Llamada'),('ambos','Ambos')], default='whatsapp', max_length=10)),
                ('dias_contacto', models.CharField(blank=True, max_length=20)),
                ('producto_no_catalogo', models.TextField(blank=True)),
                ('rotacion_estimada', models.CharField(default='media', max_length=10)),
                ('verificada', models.BooleanField(default=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='clinica', to=settings.AUTH_USER_MODEL)),
                ('productos_interes', models.ManyToManyField(blank=True, related_name='clinicas_interesadas',
                    to='miprimerapp.producto')),
            ],
            options={'verbose_name': 'Clínica', 'verbose_name_plural': 'Clínicas', 'ordering': ['region', 'nombre_clinica']},
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente','Pendiente'),('en_preparacion','En preparación'),
                    ('enviado','Enviado'),('entregado','Entregado'),('cancelado','Cancelado')],
                    default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='pedidos', to='miprimerapp.clinica')),
            ],
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos', 'ordering': ['-fecha_creacion']},
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('precio_unitario', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='detalles', to='miprimerapp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    to='miprimerapp.producto')),
            ],
            options={'verbose_name': 'Detalle de pedido', 'verbose_name_plural': 'Detalles de pedido'},
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='historial', to='miprimerapp.pedido')),
            ],
            options={'verbose_name': 'Historial de estado', 'ordering': ['fecha']},
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='carrito_items', to='miprimerapp.clinica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    to='miprimerapp.producto')),
            ],
            options={'verbose_name': 'Ítem de carrito', 'ordering': ['agregado'],
                     'unique_together': {('clinica', 'producto')}},
        ),
    ]
