# Generated by Django 6.0.6 on 2026-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritoitem',
            options={'ordering': ['agregado'], 'verbose_name': 'Ítem de carrito', 'verbose_name_plural': 'Ítems de carrito'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['fecha'], 'verbose_name': 'Historial de estado', 'verbose_name_plural': 'Historial de estados'},
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='dias_contacto',
            field=models.CharField(blank=True, choices=[('lunes_viernes', 'Lunes a Viernes'), ('lunes_sabado', 'Lunes a Sábado'), ('manana', 'Solo mañanas (9:00–13:00)'), ('tarde', 'Solo tardes (14:00–18:00)'), ('cualquier_dia', 'Cualquier día/horario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='medio_contacto',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada telefónica'), ('ambos', 'Cualquiera de los dos')], default='whatsapp', max_length=10),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='region',
            field=models.CharField(choices=[('RM', 'Región Metropolitana'), ('V', 'Valparaíso'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('X', 'Los Lagos'), ('XIV', 'Los Ríos'), ('XV', 'Arica y Parinacota'), ('XVI', 'Ñuble'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='rotacion_estimada',
            field=models.CharField(choices=[('baja', 'Baja – 1 a 5 unidades / semana'), ('media', 'Media – 6 a 20 unidades / semana'), ('alta', 'Alta – 21 a 50 unidades / semana'), ('muy_alta', 'Muy alta – más de 50 unidades / semana')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='region',
            field=models.CharField(blank=True, choices=[('RM', 'Región Metropolitana'), ('V', 'Valparaíso'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('X', 'Los Lagos'), ('XIV', 'Los Ríos'), ('XV', 'Arica y Parinacota'), ('XVI', 'Ñuble'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='tipo_consulta',
            field=models.CharField(choices=[('info', 'Quiero más información'), ('inscripcion', 'Inscribir mi clínica'), ('pedido', 'Hacer un pedido'), ('soporte', 'Soporte técnico'), ('factura', 'Consulta de facturación'), ('otro', 'Otro')], default='info', max_length=15),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_minima_volumen',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad mínima para activar el precio especial', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.PositiveIntegerField(default=0, help_text='Costo del producto (base para B2D)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_b2d',
            field=models.PositiveIntegerField(blank=True, help_text='Precio canal dental (se calcula automáticamente si se deja vacío)', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_volumen',
            field=models.PositiveIntegerField(blank=True, help_text='Precio especial al comprar la cantidad mínima o más', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pronto_a_vencer',
            field=models.BooleanField(default=False, help_text='Activa precio especial: costo × 1.19'),
        ),
    ]
