# Generated by Django 6.0.6 on 2026-06-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0002_alter_carritoitem_options_and_more'),
        ('miprimerapp', '0003_ajuste_inventario_producto_sugerido'),
    ]

    operations = [
    ]
