# Generated by Django 6.0.6 on 2026-06-16 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0004_merge_20260616_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalclinica',
            options={'ordering': ['nombre'], 'verbose_name': 'Personal de clínica', 'verbose_name_plural': 'Personal de clínicas'},
        ),
        migrations.AlterModelOptions(
            name='stockminimo',
            options={'verbose_name': 'Stock mínimo', 'verbose_name_plural': 'Stock mínimos'},
        ),
        migrations.AlterModelOptions(
            name='ventastock',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta de stock', 'verbose_name_plural': 'Ventas de stock'},
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalclinica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productosugerido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ventastock',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ventastock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
