# Generated by Django 6.0.6 on 2026-06-16 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0005_alter_personalclinica_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Casa', help_text='Ej: Casa, Trabajo', max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=80)),
                ('region', models.CharField(choices=[('RM', 'Región Metropolitana'), ('V', 'Valparaíso'), ('VI', "O'Higgins"), ('VII', 'Maule'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('X', 'Los Lagos'), ('XIV', 'Los Ríos'), ('XV', 'Arica y Parinacota'), ('XVI', 'Ñuble'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo')], max_length=5)),
                ('referencia', models.CharField(blank=True, help_text='Ej: Depto 302, casa azul', max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de despacho',
                'verbose_name_plural': 'Direcciones de despacho',
                'ordering': ['-principal', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario_preferido', models.CharField(choices=[('manana', 'Mañana (9:00–13:00)'), ('tarde', 'Tarde (14:00–18:00)'), ('cualquiera', 'Cualquier horario')], default='cualquiera', max_length=15)),
                ('dias_disponibles', models.CharField(choices=[('lunes_viernes', 'Lunes a Viernes'), ('lunes_sabado', 'Lunes a Sábado'), ('cualquier_dia', 'Cualquier día')], default='cualquier_dia', max_length=15)),
                ('observaciones_entrega', models.TextField(blank=True, help_text='Ej: Tocar timbre, no llamar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('horario', models.CharField(blank=True, max_length=15)),
                ('dias', models.CharField(blank=True, max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miprimerapp.direcciondespacho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud público',
                'verbose_name_plural': 'Solicitudes público',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('precio_unitario', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miprimerapp.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miprimerapp.solicitudpublico')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItemPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.PositiveIntegerField()),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miprimerapp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_publico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem carrito público',
                'verbose_name_plural': 'Ítems carrito público',
                'ordering': ['agregado'],
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
