# Generated by Django 6.0.6 on 2026-06-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0006_direcciondespacho_perfilusuario_solicitudpublico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dias_disponibles',
            field=models.CharField(blank=True, default='cualquier_dia', max_length=100),
        ),
    ]
