# Generated by Django 6.0.6 on 2026-06-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0009_categoria_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='nota_resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_resueltos', to=settings.AUTH_USER_MODEL),
        ),
    ]
