# Generated by Django 6.0.6 on 2026-06-17 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0010_consultacontacto_fecha_resolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='estado_caso',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='fecha_tomado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='notas_seguimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='tomado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_tomados', to=settings.AUTH_USER_MODEL),
        ),
    ]
