# Generated by Django 6.0.6 on 2026-06-17 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0012_consultacontacto_caso_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', '📧 Email'), ('whatsapp', '💬 WhatsApp'), ('llamada', '📞 Llamada telefónica'), ('presencial', '🏢 Presencial'), ('otro', '🌐 Otro')], default='email', max_length=15)),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consulta_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_vinculadas', to='miprimerapp.consultacontacto')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='miprimerapp.consultacontacto')),
            ],
            options={
                'verbose_name': 'Nota de seguimiento',
                'verbose_name_plural': 'Notas de seguimiento',
                'ordering': ['fecha'],
            },
        ),
    ]
