# Generated by Django 6.0.6 on 2026-06-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0013_notaseguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultacontacto',
            name='canal_respuesta',
            field=models.CharField(blank=True, choices=[('email', '📧 Email'), ('whatsapp', '💬 WhatsApp'), ('llamada', '📞 Llamada telefónica'), ('presencial', '🏢 Presencial'), ('otro', '🌐 Otro')], default='email', max_length=15),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='dias_respuesta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='horario_respuesta',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana (9:00–13:00)'), ('tarde', 'Tarde (14:00–18:00)'), ('cualquiera', 'Cualquier horario')], default='cualquiera', max_length=15),
        ),
    ]
