# Generated by Django 6.0.6 on 2026-06-18 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0014_consultacontacto_canal_respuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra con factura'), ('inicial', 'Stock inicial / ajuste')], default='compra', max_length=10)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('numero_factura', models.CharField(blank=True, max_length=80)),
                ('fecha_compra', models.DateField()),
                ('flete_total', models.PositiveIntegerField(default=0, help_text='Valor total del flete. Se reparte proporcionalmente entre los productos.')),
                ('motivo', models.TextField(blank=True, help_text='Obligatorio para stock inicial o ajuste.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra a proveedor',
                'verbose_name_plural': 'Compras a proveedores',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='LoteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, max_length=80)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.PositiveIntegerField(default=0, help_text='Costo por unidad SIN IVA ni flete.')),
                ('actualizo_precio', models.BooleanField(default=False, help_text='True si al ingresar este lote se actualizó el precio de venta.')),
                ('notas', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='miprimerapp.compraproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='miprimerapp.producto')),
            ],
            options={
                'verbose_name': 'Lote de compra',
                'verbose_name_plural': 'Lotes de compra',
            },
        ),
    ]
