# Generated by Django 6.0.6 on 2026-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0015_compraproveedor_lotecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecompra',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que quedan de este lote (se actualiza con cada venta).'),
        ),
    ]
