# Generated by Django 6.0.6 on 2026-06-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0016_lotecompra_cantidad_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLoteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_usados', to='miprimerapp.detallepedido')),
                ('detalle_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_usados', to='miprimerapp.detallesolicitudpublico')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='miprimerapp.lotecompra')),
            ],
            options={
                'verbose_name': 'Detalle de lote en venta',
                'verbose_name_plural': 'Detalles de lote en ventas',
            },
        ),
    ]
