# Generated by Django 6.0.6 on 2026-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0018_historialestado_cambiado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudpublico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15),
        ),
    ]
