# Generated by Django 6.0.6 on 2026-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0019_alter_pedido_estado_alter_solicitudpublico_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultacontacto',
            name='nombre_clinica',
        ),
        migrations.AddField(
            model_name='consultacontacto',
            name='es_clinica',
            field=models.BooleanField(default=False, verbose_name='Soy Clínica Dental'),
        ),
        migrations.AlterField(
            model_name='consultacontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
