# Generated by Django 6.0.6 on 2026-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0020_remove_consultacontacto_nombre_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultacontacto',
            name='tipo_consulta',
            field=models.CharField(choices=[('info', 'Quiero más información'), ('inscripcion', 'Inscribir mi clínica'), ('pedido', 'Hacer un pedido'), ('soporte', 'Soporte técnico'), ('factura', 'Consulta de facturación'), ('reclamo', 'Reclamo'), ('felicitacion', 'Felicitaciones'), ('otro', 'Otro')], default='info', max_length=15),
        ),
    ]
