# Generated by Django 6.0.6 on 2026-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0021_alter_consultacontacto_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotecompra',
            name='no_vence',
            field=models.BooleanField(default=False, help_text='Marcar si este producto no tiene fecha de vencimiento (ej. cepillos, dispositivos).'),
        ),
    ]
