# Generated by Django 6.0.6 on 2026-06-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0022_lotecompra_no_vence'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublico',
            name='pago_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudpublico',
            name='token_pago',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
